// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SalesAdmin', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SalesAdmin', async function() {
    //let driver = await new Builder().forBrowser("chrome").build();
    await driver.get("http://103.203.132.254:8888/");
    

    //add to do
    //for login Section
    await driver.findElement(By.name("username")).sendKeys("Admin",Key.RETURN) //adding user name
    await driver.findElement(By.name("password")).sendKeys("password",Key.RETURN) //adding password
    // Test name: SalesAdmin
    // Step # | name | target | value
    // 1 | open | /admin/dashboard | 
    await driver.get("http://103.203.132.254:8888/admin/order-management/list")
    console.log("Reached here ")
    // 2 | setWindowSize | 1312x741 | 
    await driver.manage().window().setRect({ width: 1312, height: 741 })
    // 3 | click | css=.nav-item:nth-child(6) p | 
    await driver.findElement(By.css(".nav-item:nth-child(6) p")).click()
    console.log("success 1")
    // 4 | click | css=#order-management .nav-item:nth-child(2) .sidebar-normal | 
   // await driver.findElement(By.css("#order-management .nav-item:nth-child(2) .sidebar-normal")).click()
    console.log("success 2")
    // 5 | click | css=#order-management .nav-item:nth-child(3) .sidebar-normal | 
   // await driver.findElement(By.css("#order-management .nav-item:nth-child(3) .sidebar-normal")).click()
    // 6 | click | css=tr:nth-child(1) .text-success > .material-icons | 
    await driver.findElement(By.css("tr:nth-child(1) .text-success > .material-icons")).click()
    console.log("success till here ")
    // 7 | runScript | window.scrollTo(0,0) | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 8 | click | css=#vs19__combobox .vs__search | 
   // await driver.findElement(By.css("#vs19__combobox .vs__search")).click()
    // 9 | click | id=vs19__option-0 | 
    //await driver.findElement(By.id("vs19__option-0")).click()
    // 10 | mouseDown | id=vs20__combobox | 
    {
     // const element = await driver.findElement(By.id("vs20__combobox"))
      //await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 11 | mouseUp | id=vs20__listbox | 
    {
      //const element = await driver.findElement(By.id("vs20__listbox"))
//await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 12 | click | css=.vs--open | 
   // await driver.findElement(By.css(".vs--open")).click()
    // 14 | click | css=#vs22__combobox .vs__search | 
    await driver.findElement(By.css("#vs22__combobox .vs__search")).click()
    // 15 | click | id=vs22__option-2 | 
    await driver.findElement(By.id("vs22__option-2")).click()
  })
})
